export const skills = [
	"JavaScript",
	"Python",
	"Java",
	"C++",
	"HTML",
	"CSS",
	"SQL",
	"Ruby",
	"PHP",
	"Swift",
	"Kotlin",
	"TypeScript",
	"Go",
	"Rust",
	"R",
	"C#",
	"MATLAB",
	"Perl",
	"Shell Scripting",
	"Scala",
	"Dart",
	"Lua",
	"Groovy",
	"Haskell",
	"Assembly Language",
	"Objective-C",
	"PowerShell",
	"F#",
	"Visual Basic",
	"COBOL",
	"Fortran",
	"Prolog",
	"Lisp",
	"Pascal",
	"Ada",
	"VHDL",
	"Verilog",
	"COOL",
	"Smalltalk",
	"ActionScript",
	"CoffeeScript",
	"GraphQL",
	"Elixir",
	"Clojure",
	"Erlang",
	"Bash Scripting",
	"Golang",
	"Ruby on Rails",
	"Django",
	"Laravel",
	"Spring Framework",
	".NET Framework",
	"React.js",
	"Angular",
	"Vue.js",
	"Node.js",
	"Express.js",
	"Flask",
	"MongoDB",
	"MySQL",
	"PostgreSQL",
	"Oracle",
	"AWS (Amazon Web Services)",
	"Azure",
	"Docker",
	"Kubernetes",
	"Git",
	"Jenkins",
	"Agile Development",
	"Test-Driven Development (TDD)",
	"DevOps",
	"Data Structures",
	"Algorithms",
	"Machine Learning",
	"Artificial Intelligence",
	"Communication Skills",
	"Problem Solving",
	"Leadership",
	"Teamwork",
	"Time Management",
	"Creativity",
	"Critical Thinking",
	"Adaptability",
	"Analytical Skills",
	"Presentation Skills",
	"Project Management",
	"Negotiation Skills",
	"Research Skills",
	"Customer Service",
	"Data Analysis",
	"Decision Making",
	"Conflict Resolution",
	"Emotional Intelligence",
	"Networking",
	"Organizational Skills",
	"Financial Literacy",
	"Sales and Marketing",
	"Public Speaking",
	"Writing and Editing",
	"Graphic Design",
	"User Experience (UX) Design",
	"User Interface (UI) Design",
	"Problem Analysis",
	"Quality Assurance",
	"Risk Management",
	"Strategic Planning",
	"Entrepreneurship",
	"Vendor Management",
	"Supply Chain Management",
	"Customer Relationship Management (CRM)",
	"Business Intelligence",
	"Market Research",
	"Human Resources",
	"Training and Development",
	"Event Planning",
	"Foreign Language Proficiency",
	"Conflict Management",
	"Coaching and Mentoring",
	"Decision Analysis",
	"Negotiation and Persuasion",
	"Cultural Awareness",
	"Change Management",
	"Digital Marketing",
	"SEO (Search Engine Optimization)",
	"Social Media Management",
	"Content Writing",
	"Public Relations",
	"Data Visualization",
	"Statistical Analysis",
	"Ethical Hacking",
	"Cybersecurity",
	"Risk Assessment",
	"Incident Response",
	"Leadership Development",
	"Emotional Intelligence",
	"Business Strategy",
	"Financial Analysis",
	"Project Coordination",
	"Event Management",
	"Vendor Negotiation",
];
